-- @ This module provides a mapping of Flux properties to Roblox properties

return {
    bg = "BackgroundColor3",
    textColor = "TextColor3",
    text = "Text",
    anchor = "AnchorPoint",
    textOpacity = "TextTransparency",
    textSize = "TextSize",
    font = "FontFamily",
    list = "UIListLayout",
    ha = "HorizontalAlignment",
    va = "VerticalAlignment",
    img = "Image",
    imgColor = "ImageColor3",
    imgScaleType = "ScaleType",
    imgOpacity = "ImageTransparency",
    p = "Padding",
    clip = "ClipsDescendants",
    z = "ZIndex",
    sBorder = "BorderSizePixel",
    border = "UIStroke",
    borderColor = "UIStroke",
    bopacity = "Transparency",
    borderjoin = "LineJoinMode",
    opacity = "BackgroundTransparency",
    align = "align", --remove
    round = "CornerRadius",
    ps = "Position",
    psx = "Position",
    psy = "Position",
    textX = "TextXAlignment",
    textY = "TextYAlignment",
    s = "Size",
    sx = "Size",
    sy = "Size",
    cf = "CFrame",
    vec3 = "Vector3",
    vec2 = "Vector2",
}